#!/usr/bin/env node
/**
 * Single-source codegen for the notebook's Python.
 *
 *   data/nifty100_snapshot.json  ->  python/engine.py  (generated block)
 *   python/engine.py             ->  src/utils/pythonEngineSource.ts
 *
 * The Python lives in a real .py file so it can be compiled and unit-tested
 * directly. The TS module is produced with JSON.stringify, so escaping is done
 * by the serialiser rather than by hand -- the class of bug where a JS template
 * literal silently ate `\w`, `\s` and `\b` out of the Python regexes cannot
 * recur.
 *
 * Run: npm run build:python   (verify-only: npm run build:python -- --check)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const SNAPSHOT = path.join(root, 'data', 'nifty100_snapshot.json');
const ENGINE_PY = path.join(root, 'python', 'engine.py');
const TS_OUT = path.join(root, 'src', 'utils', 'pythonEngineSource.ts');
const SNAPSHOT_TS_OUT = path.join(root, 'src', 'data', 'nifty100Snapshot.ts');

const START = '# === GENERATED:NIFTY100 START ===';
const END = '# === GENERATED:NIFTY100 END ===';

const checkOnly = process.argv.includes('--check');

function pyList(symbols) {
  const lines = [];
  for (let i = 0; i < symbols.length; i += 6) {
    lines.push('    ' + symbols.slice(i, i + 6).map((s) => `"${s}"`).join(', ') + ',');
  }
  return lines.join('\n');
}

function injectSnapshot(source, snapshot) {
  const startIdx = source.indexOf(START);
  const endIdx = source.indexOf(END);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(`Could not locate GENERATED:NIFTY100 markers in ${ENGINE_PY}`);
  }
  const block = [
    START,
    'NIFTY100_PROVENANCE = {',
    `    "source_url": ${JSON.stringify(snapshot.source_url)},`,
    `    "retrieved_at_utc": ${JSON.stringify(snapshot.retrieved_at_utc)},`,
    `    "as_of_date": ${JSON.stringify(snapshot.as_of_date)},`,
    `    "sha256_of_source_csv": ${JSON.stringify(snapshot.sha256_of_source_csv)},`,
    `    "count": ${snapshot.count},`,
    '}',
    '',
    '# Cached snapshot, NOT a live feed. Current as of',
    '# NIFTY100_PROVENANCE["as_of_date"]; the index is rebalanced periodically.',
    'NIFTY100_FALLBACK_SYMBOLS = [',
    pyList(snapshot.symbols),
    ']',
    END,
  ].join('\n');
  return source.slice(0, startIdx) + block + source.slice(endIdx + END.length);
}

/**
 * The browser's copy of the snapshot. It used to be maintained by hand while
 * claiming to be generated by a script that never existed, so the two engines
 * could silently disagree about the universe.
 */
function buildSnapshotModule(snapshot) {
  const rows = [];
  for (let i = 0; i < snapshot.symbols.length; i += 8) {
    rows.push('  ' + snapshot.symbols.slice(i, i + 8).map((s) => `'${s}'`).join(', ') + ',');
  }
  return [
    '// GENERATED FILE - DO NOT EDIT BY HAND.',
    '// Source of truth: data/nifty100_snapshot.json',
    '// Regenerate with: npm run build:python',
    '//',
    '// Single shared snapshot of the Nifty 100 constituent list. Both the browser',
    '// engine and the generated Colab notebook derive their fallback universe from',
    '// this file, so the two can never drift apart.',
    'export interface Nifty100Provenance {',
    '  source_url: string;',
    '  retrieved_at_utc: string;',
    '  as_of_date: string;',
    '  sha256_of_source_csv: string;',
    '  count: number;',
    '}',
    '',
    'export const NIFTY100_PROVENANCE: Nifty100Provenance = {',
    `  source_url: ${JSON.stringify(snapshot.source_url)},`,
    `  retrieved_at_utc: ${JSON.stringify(snapshot.retrieved_at_utc)},`,
    `  as_of_date: ${JSON.stringify(snapshot.as_of_date)},`,
    `  sha256_of_source_csv: ${JSON.stringify(snapshot.sha256_of_source_csv)},`,
    `  count: ${snapshot.count},`,
    '};',
    '',
    '/**',
    ' * Cached snapshot, NOT a live feed. It was current as of',
    ' * NIFTY100_PROVENANCE.as_of_date; the index is rebalanced periodically, so',
    ' * always describe this list as "cached (as of <as_of_date>)" in the UI.',
    ' */',
    'export const NIFTY100_FALLBACK_SYMBOLS: readonly string[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
}

function buildTsModule(pythonSource) {
  return [
    '// GENERATED FILE - DO NOT EDIT BY HAND.',
    '// Source of truth: python/engine.py',
    '// Regenerate with: npm run build:python',
    '//',
    '// The Python payload is embedded via JSON.stringify rather than a template',
    '// literal, so backslash escapes in the Python (\\w, \\s, \\b) survive intact.',
    'export const PYTHON_ENGINE_SOURCE: string =',
    '  ' + JSON.stringify(pythonSource) + ';',
    '',
    '/** Back-compatible alias used by the notebook builder and the Colab viewer. */',
    'export const PYTHON_COLAB_FULL_SCRIPT: string = PYTHON_ENGINE_SOURCE;',
    '',
  ].join('\n');
}

const snapshot = JSON.parse(readFileSync(SNAPSHOT, 'utf8'));
if (!Array.isArray(snapshot.symbols) || snapshot.symbols.length !== 100) {
  throw new Error(`Snapshot must contain exactly 100 symbols, found ${snapshot.symbols?.length}`);
}
if (new Set(snapshot.symbols).size !== 100) {
  throw new Error('Snapshot symbols are not unique');
}
for (const key of ['source_url', 'retrieved_at_utc', 'as_of_date', 'sha256_of_source_csv']) {
  if (!snapshot[key]) throw new Error(`Snapshot missing provenance field: ${key}`);
}

const originalPy = readFileSync(ENGINE_PY, 'utf8');
const injectedPy = injectSnapshot(originalPy, snapshot);
const tsModule = buildTsModule(injectedPy);
const snapshotModule = buildSnapshotModule(snapshot);

if (checkOnly) {
  const problems = [];
  if (originalPy !== injectedPy) {
    problems.push(`${path.relative(root, ENGINE_PY)} is out of sync with the Nifty snapshot`);
  }
  let existingTs = null;
  try {
    existingTs = readFileSync(TS_OUT, 'utf8');
  } catch {
    problems.push(`${path.relative(root, TS_OUT)} is missing`);
  }
  if (existingTs !== null && existingTs !== tsModule) {
    problems.push(`${path.relative(root, TS_OUT)} is out of sync with python/engine.py`);
  }
  let existingSnapshotTs = null;
  try {
    existingSnapshotTs = readFileSync(SNAPSHOT_TS_OUT, 'utf8');
  } catch {
    problems.push(`${path.relative(root, SNAPSHOT_TS_OUT)} is missing`);
  }
  if (existingSnapshotTs !== null && existingSnapshotTs !== snapshotModule) {
    problems.push(`${path.relative(root, SNAPSHOT_TS_OUT)} is out of sync with the Nifty snapshot`);
  }
  if (problems.length) {
    console.error('build:python --check FAILED:');
    for (const p of problems) console.error(`  - ${p}`);
    console.error('Run: npm run build:python');
    process.exit(1);
  }
  console.log(
    'build:python --check OK (engine.py, pythonEngineSource.ts and nifty100Snapshot.ts are in sync)',
  );
  process.exit(0);
}

if (originalPy !== injectedPy) writeFileSync(ENGINE_PY, injectedPy);
writeFileSync(TS_OUT, tsModule);
writeFileSync(SNAPSHOT_TS_OUT, snapshotModule);
console.log(
  `build:python OK -> ${path.relative(root, TS_OUT)}, ${path.relative(root, SNAPSHOT_TS_OUT)} ` +
    `(${injectedPy.split('\n').length} python lines, ${snapshot.count} symbols as of ${snapshot.as_of_date})`,
);
